import z from 'zod'

const categorySchema = z.object({
  id: z.string(),
  name: z.string(),
})

const transactionSchema = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  amount: z.number(),
  isRecipient: z.boolean().default(false),
  registeredDate: z.string(),
  category: categorySchema,
  createdBy: z.string(),
  group: z.string().nullable().optional(),
})

export type Category = z.infer<typeof categorySchema>
export type Transaction = z.infer<typeof transactionSchema>

export const transactionCategories: Category[] = [
  {
    id: '1',
    name: 'Alimentation',
  },
  {
    id: '2',
    name: 'Transport',
  },
  {
    id: '3',
    name: 'Logement',
  },
  {
    id: '4',
    name: 'Hobbies',
  },
]

export const transactions: Transaction[] = [
  // =========================
  // Alimentation - 20
  // =========================
  {
    id: 'tx-food-001',
    name: 'IGA',
    description: 'Épicerie de la semaine',
    amount: 86.42,
    isRecipient: true,
    registeredDate: '2026-08-27T17:32:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: 'Amis',
  },
  {
    id: 'tx-food-002',
    name: "McDonald's",
    description: 'Repas du midi',
    amount: 14.85,
    isRecipient: false,
    registeredDate: '2026-08-26T12:15:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-003',
    name: 'Tim Hortons',
    description: 'Café et déjeuner',
    amount: 8.75,
    isRecipient: false,
    registeredDate: '2026-08-25T08:42:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-004',
    name: 'Costco',
    description: 'Épicerie et produits alimentaires',
    amount: 124.63,
    isRecipient: false,
    registeredDate: '2026-08-23T15:21:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-005',
    name: 'St-Hubert',
    description: 'Souper',
    amount: 38.5,
    isRecipient: false,
    registeredDate: '2026-08-21T18:47:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-006',
    name: 'Metro',
    description: 'Fruits et légumes',
    amount: 42.18,
    isRecipient: false,
    registeredDate: '2026-08-19T16:05:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-007',
    name: 'Subway',
    description: 'Dîner',
    amount: 13.42,
    isRecipient: false,
    registeredDate: '2026-08-17T12:36:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-008',
    name: 'Walmart',
    description: 'Épicerie',
    amount: 67.91,
    isRecipient: false,
    registeredDate: '2026-08-15T14:18:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-009',
    name: 'Pizza Pizza',
    description: 'Souper entre amis',
    amount: 29.75,
    isRecipient: false,
    registeredDate: '2026-08-12T19:22:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-010',
    name: 'Super C',
    description: 'Épicerie',
    amount: 73.26,
    isRecipient: false,
    registeredDate: '2026-08-09T11:43:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-011',
    name: 'Loblaws',
    description: 'Épicerie',
    amount: 91.37,
    isRecipient: false,
    registeredDate: '2026-08-07T16:25:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-012',
    name: 'A&W',
    description: 'Repas du soir',
    amount: 18.64,
    isRecipient: false,
    registeredDate: '2026-08-05T19:11:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-013',
    name: 'Provigo',
    description: 'Épicerie',
    amount: 54.29,
    isRecipient: false,
    registeredDate: '2026-08-03T13:47:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-014',
    name: 'Starbucks',
    description: 'Café',
    amount: 7.85,
    isRecipient: false,
    registeredDate: '2026-07-31T09:18:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-015',
    name: 'Benny & Co.',
    description: 'Souper',
    amount: 32.47,
    isRecipient: false,
    registeredDate: '2026-07-29T18:36:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-016',
    name: 'Marché Richelieu',
    description: 'Fruits et légumes',
    amount: 31.92,
    isRecipient: false,
    registeredDate: '2026-07-26T14:52:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-017',
    name: "Domino's Pizza",
    description: 'Pizza',
    amount: 27.63,
    isRecipient: false,
    registeredDate: '2026-07-23T20:14:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-018',
    name: 'Metro',
    description: 'Produits alimentaires',
    amount: 76.48,
    isRecipient: false,
    registeredDate: '2026-07-20T15:31:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-019',
    name: 'Tim Hortons',
    description: 'Café et pâtisserie',
    amount: 11.25,
    isRecipient: false,
    registeredDate: '2026-07-17T08:23:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-food-020',
    name: 'IGA',
    description: 'Épicerie',
    amount: 103.74,
    isRecipient: false,
    registeredDate: '2026-07-14T17:42:00',
    category: {
      id: '1',
      name: 'Alimentation',
    },
    createdBy: 'user-001',
    group: undefined,
  },

  // =========================
  // Transport - 20
  // =========================
  {
    id: 'tx-transport-001',
    name: 'Shell',
    description: 'Essence',
    amount: 62.34,
    isRecipient: false,
    registeredDate: '2026-08-27T18:12:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-002',
    name: 'STM',
    description: 'Carte mensuelle',
    amount: 97.0,
    isRecipient: false,
    registeredDate: '2026-08-26T09:05:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-003',
    name: 'Esso',
    description: 'Essence',
    amount: 54.72,
    isRecipient: false,
    registeredDate: '2026-08-24T17:34:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-004',
    name: 'Canadian Tire',
    description: 'Entretien automobile',
    amount: 128.49,
    isRecipient: false,
    registeredDate: '2026-08-22T13:47:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-005',
    name: 'Uber',
    description: 'Déplacement',
    amount: 21.63,
    isRecipient: false,
    registeredDate: '2026-08-20T22:14:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-006',
    name: 'Petro-Canada',
    description: 'Essence',
    amount: 58.91,
    isRecipient: false,
    registeredDate: '2026-08-18T16:42:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-007',
    name: 'Garage Auto Plus',
    description: 'Changement d’huile',
    amount: 89.99,
    isRecipient: false,
    registeredDate: '2026-08-16T10:21:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-008',
    name: 'Shell',
    description: 'Essence',
    amount: 61.27,
    isRecipient: false,
    registeredDate: '2026-08-13T18:03:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-009',
    name: 'Communauto',
    description: 'Location de voiture',
    amount: 34.5,
    isRecipient: false,
    registeredDate: '2026-08-11T15:37:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-010',
    name: 'Esso',
    description: 'Essence',
    amount: 49.83,
    isRecipient: false,
    registeredDate: '2026-08-08T17:51:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-011',
    name: 'STM',
    description: 'Billet de transport',
    amount: 4.75,
    isRecipient: false,
    registeredDate: '2026-08-06T08:32:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-012',
    name: 'Shell',
    description: 'Essence',
    amount: 57.18,
    isRecipient: false,
    registeredDate: '2026-08-04T17:26:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-013',
    name: 'Uber',
    description: 'Retour à la maison',
    amount: 18.92,
    isRecipient: false,
    registeredDate: '2026-08-02T23:14:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-014',
    name: 'Petro-Canada',
    description: 'Essence',
    amount: 64.37,
    isRecipient: false,
    registeredDate: '2026-07-30T18:47:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-015',
    name: 'Canadian Tire',
    description: 'Lave-auto',
    amount: 15.99,
    isRecipient: false,
    registeredDate: '2026-07-28T12:21:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-016',
    name: 'Esso',
    description: 'Essence',
    amount: 53.46,
    isRecipient: false,
    registeredDate: '2026-07-25T17:13:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-017',
    name: 'Communauto',
    description: 'Location de voiture',
    amount: 41.2,
    isRecipient: false,
    registeredDate: '2026-07-22T14:38:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-018',
    name: 'Shell',
    description: 'Essence',
    amount: 59.82,
    isRecipient: false,
    registeredDate: '2026-07-19T16:52:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-019',
    name: 'Uber',
    description: 'Déplacement',
    amount: 24.71,
    isRecipient: false,
    registeredDate: '2026-07-16T21:43:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-transport-020',
    name: 'Petro-Canada',
    description: 'Essence',
    amount: 56.28,
    isRecipient: false,
    registeredDate: '2026-07-13T18:26:00',
    category: {
      id: '2',
      name: 'Transport',
    },
    createdBy: 'user-001',
    group: undefined,
  },

  // =========================
  // Logement - 20
  // =========================
  {
    id: 'tx-housing-001',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 74.36,
    isRecipient: false,
    registeredDate: '2026-08-27T09:14:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-002',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-08-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-003',
    name: 'Internet',
    description: 'Facture internet mensuelle',
    amount: 59.95,
    isRecipient: false,
    registeredDate: '2026-08-05T10:32:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-004',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 68.24,
    isRecipient: false,
    registeredDate: '2026-07-27T09:18:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-005',
    name: 'RONA',
    description: 'Matériel pour réparation',
    amount: 43.87,
    isRecipient: false,
    registeredDate: '2026-07-22T14:51:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-006',
    name: 'Internet',
    description: 'Facture internet mensuelle',
    amount: 59.95,
    isRecipient: false,
    registeredDate: '2026-07-05T10:27:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-007',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-07-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-008',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 81.52,
    isRecipient: false,
    registeredDate: '2026-06-27T09:12:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-009',
    name: 'IKEA',
    description: 'Meuble pour la maison',
    amount: 219.99,
    isRecipient: false,
    registeredDate: '2026-06-21T13:42:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-010',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-06-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-011',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 72.18,
    isRecipient: false,
    registeredDate: '2026-05-27T09:15:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-012',
    name: 'Internet',
    description: 'Facture internet mensuelle',
    amount: 59.95,
    isRecipient: false,
    registeredDate: '2026-05-05T10:31:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-013',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-05-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-014',
    name: 'RONA',
    description: 'Produits pour entretien',
    amount: 37.42,
    isRecipient: false,
    registeredDate: '2026-04-24T15:37:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-015',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 91.63,
    isRecipient: false,
    registeredDate: '2026-04-27T09:11:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-016',
    name: 'Internet',
    description: 'Facture internet mensuelle',
    amount: 59.95,
    isRecipient: false,
    registeredDate: '2026-04-05T10:29:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-017',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-04-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-018',
    name: 'IKEA',
    description: 'Articles pour la maison',
    amount: 84.99,
    isRecipient: false,
    registeredDate: '2026-03-22T13:24:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-019',
    name: 'Hydro-Québec',
    description: 'Facture d’électricité',
    amount: 77.42,
    isRecipient: false,
    registeredDate: '2026-03-27T09:08:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
  {
    id: 'tx-housing-020',
    name: 'Loyer',
    description: 'Paiement du loyer',
    amount: 1250.0,
    isRecipient: false,
    registeredDate: '2026-03-01T08:00:00',
    category: {
      id: '3',
      name: 'Logement',
    },
    createdBy: 'user-001',
    group: undefined,
  },
]
